name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:                    # Global permissions configuration starts here
  contents: write                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install
      run: |
        make install
        make rust-install
    - name: Format
      run: |
        make format
        make rust-format
    - name: Lint
      run: |
        make lint
        make rust-lint
    - name: Test
      run: |
        make test
        make rust-test
    - name: Run
      run: |
        make run
        make rust-run